---
- name: Install Python Docker dependencies
  ansible.builtin.include_tasks: dependency.yml

- name: Run preflight checks
  ansible.builtin.include_tasks: preflight.yml

- name: Initialize Docker Swarm
  ansible.builtin.include_tasks: swarm-init.yml

- name: Ensure deploy directory exists
  ansible.builtin.file:
    path: "{{ node_exporter_deploy_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [dirs]

- name: Deploy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ node_exporter_deploy_dir }}/docker-compose.yaml"
    mode: "0644"
  tags: [compose]

- name: Deploy monitoring stack to Docker Swarm
  community.docker.docker_stack:
    name: "{{ node_exporter_stack_name }}"
    compose:
      - "{{ node_exporter_deploy_dir }}/docker-compose.yaml"
    state: present
  tags: [stack]
