---
- name: Install nginx (Debian)
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install nginx (RedHat)
  ansible.builtin.dnf:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable and start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
