---
- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Reset SSH connection to apply group changes
  ansible.builtin.meta: reset_connection
