---
- name: Converge
  hosts: all
  become: true

  vars:
    users:
      - name: testuser
        servers: ['all']
        user_groups: [sudo]
    user_groups:
      - sudo

  roles:
    - role: users
