---
all:
  vars:
    ansible_user: ansible
    ansible_password: password
    ansible_become_password: password

  children:
    rocky:
      hosts:
        rocky1:
          ansible_host: 127.0.0.1
          ansible_port: 3224
        rocky2:
          ansible_host: 127.0.0.1
          ansible_port: 3225
