---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install Docker and Python bindings
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-docker
          - python3-jsondiff
          - python3-yaml
        state: present
        update_cache: true

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Initialize Docker Swarm
      ansible.builtin.command: docker swarm init --advertise-addr 127.0.0.1
      changed_when: true
      register: swarm_init
      failed_when:
        - swarm_init.rc != 0
        - "'already part of a swarm' not in swarm_init.stderr"
