---
docker_secrets:
  - name: VAULT_ADDR
    data: "{{ vault_addr }}"
  - name: VAULT_USERNAME
    data: "{{ vault_username }}"
  - name: VAULT_PASSWORD
    data: "{{ vault_password }}"
  - name: VAULT_POS_USERNAME
    data: "{{ vault_pos_username }}"
  - name: VAULT_POS_PASSWORD
    data: "{{ vault_pos_password }}"
  - name: VAULT_ACCOUNT_SERVICE_PATH
    data: "{{ vault_account_service_path }}"
  - name: VAULT_ADMIN_FRONTEND_PATH
    data: "{{ vault_admin_frontend_path }}"
  - name: VAULT_BILLING_SERVICE_PATH
    data: "{{ vault_billing_service_path }}"
  - name: VAULT_CASHBOX_SERVICE_PATH
    data: "{{ vault_cashbox_service_path }}"
  - name: VAULT_CONTRACTOR_SERVICE_PATH
    data: "{{ vault_contractor_service_path }}"
  - name: VAULT_CURRENCY_SERVICE_PATH
    data: "{{ vault_currency_service_path }}"
  - name: VAULT_DESKTOP_APP_MANAGER_PATH
    data: "{{ vault_desktop_app_manager_path }}"
  - name: VAULT_DESKTOP_AP_SERVICE_PATH
    data: "{{ vault_desktop_ap_service_path }}"
  - name: VAULT_EMPLOYEE_SERVICE_PATH
    data: "{{ vault_employee_service_path }}"
  - name: VAULT_EXCEL_SERVICE_PATH
    data: "{{ vault_excel_service_path }}"
  - name: VAULT_ITEM_SERVICE_PATH
    data: "{{ vault_item_service_path }}"
  - name: VAULT_MANUFACTURE_SERVICE_PATH
    data: "{{ vault_manufacture_service_path }}"
  - name: VAULT_OPTOM_SELLER_SERVICE_PATH
    data: "{{ vault_optom_seller_service_path }}"
  - name: VAULT_ORGANIZATION_BINDING_SERVICE_PATH
    data: "{{ vault_organization_binding_service_path }}"
  - name: VAULT_PRICE_SERVICE_PATH
    data: "{{ vault_price_service_path }}"
  - name: VAULT_PRINT_SERVICE_PATH
    data: "{{ vault_print_service_path }}"
  - name: VAULT_PUSH_UPDATE_SERVICE_PATH
    data: "{{ vault_push_update_service_path }}"
  - name: VAULT_REDIS_SERVICE_PATH
    data: "{{ vault_redis_service_path }}"
  - name: VAULT_REFERENCE_DATA_AGGREGATOR_SERVICE_PATH
    data: "{{ vault_reference_data_aggregator_service_path }}"
  - name: VAULT_REPORT_SERVICE_PATH
    data: "{{ vault_report_service_path }}"
  - name: VAULT_ROLE_SERVICE_PATH
    data: "{{ vault_role_service_path }}"
  - name: VAULT_SETTINGS_SERVICE_PATH
    data: "{{ vault_settings_service_path }}"
  - name: VAULT_SFA_SERVICE_PATH
    data: "{{ vault_sfa_service_path }}"
  - name: VAULT_TASK_BOARD_SERVICE_PATH
    data: "{{ vault_task_board_service_path }}"
  - name: VAULT_TELEGRAM_ADMIN_BOT_SERVICE_PATH
    data: "{{ vault_telegram_admin_bot_service_path }}"
  - name: VAULT_TELEGRAM_ORDER_BOT_FRONTEND_SERVICE_PATH
    data: "{{ vault_telegram_order_bot_frontend_service_path }}"
  - name: VAULT_TELEGRAM_ORDER_BOT_SERVICE_PATH
    data: "{{ vault_telegram_order_bot_service_path }}"
  - name: VAULT_WAREHOUSE_OPERATION_SERVICE_PATH
    data: "{{ vault_warehouse_operation_service_path }}"
  - name: VAULT_WAREHOUSE_OPERATION_SERV_SERVICE_PATH
    data: "{{ vault_warehouse_operation_serv_service_path }}"
  - name: VAULT_WAREHOUSE_SERVICE_PATH
    data: "{{ vault_warehouse_service_path }}"
  - name: VAULT_AIRBYTE_SERVICE_PATH
    data: "{{ vault_airbyte_service_path }}"
  - name: VAULT_POS_PATH
    data: "{{ vault_pos_path }}"
