---
timezone: "Asia/Tashkent"
ansible_ssh_private_key_file: "~/.ssh/id_rsa"

SERVICE_NAME: project-a-backend
IMAGE: harbor.imv.uz/project-a/backend:dev
STACK_NAME: project-a
HARBOR_ENABLED: true
ENVIRONMENTS:
  TZ: "Asia/Tashkent"
  DB_HOST: "10.0.1.20"
  DB_PASSWORD: "{{ vault_db_password }}"
PORTS:
  - target: 8080
    published: 8080
    protocol: tcp
RESOURCES:
  limits:
    cpus: "0.5"
    memory: 256M
  reservations:
    cpus: "0.25"
    memory: 128M

nginx_sites:
  - name: project-a
    server_name: dev.project-a.example.com
    listen_port: 80
    listen_ssl: false
    ssl_certificate: ""
    ssl_certificate_key: ""
    root: /var/www/project-a
    index: index.html
    access_log: /var/log/nginx/project-a_access.log
    error_log: /var/log/nginx/project-a_error.log
    log_format: json
    use_allowlist: false
    locations:
      - path: /
        proxy_pass: http://127.0.0.1:8080
        extra: |
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
    extra_config: ""

users:
  - name: ahmad
    servers: ['all']
    user_groups: [sudo]
    ssh_keys:
      - ahmad
