---
all:
  vars:
    ansible_user: ahmad
    ansible_password: 123
    ansible_become_password: 123

  children:
    ubuntu:
      hosts:
        ubuntu1:
          ansible_host: 192.168.56.101
          ansible_port: 22
