---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Create test user
      ansible.builtin.user:
        name: testuser
        state: present
        create_home: true

  vars:
    zsh_users:
      - testuser

  roles:
    - role: zsh
