---
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Ensure systemd-timesyncd is installed (Debian)
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure systemd-timesyncd is running (Debian)
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Ensure chrony is installed (RedHat)
  ansible.builtin.package:
    name: chrony
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure chrony is running (RedHat)
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"
