---
all:
  vars:
    ansible_user: ansible
    ansible_password: password
    ansible_become_password: password

  children:
    alma:
      hosts:
        alma10:
          ansible_host: 127.0.0.1
          ansible_port: 3227
