---
nginx_gzip_enabled: false

nginx_ip_allowlist: []
nginx_ip_blocklist: []

nginx_vhosts:
  - name: project-a.example.com
    type: proxy
    port: 80
    ssl: false
    upstream:
      - server: 127.0.0.1:8080
