---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: true

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
