---
all:
  vars:
    ansible_user: ansible
    ansible_password: password
    ansible_become_password: password

  children:
    centos:
      hosts:
        centos8:
          ansible_host: 127.0.0.1
          ansible_port: 3226
          ansible_python_interpreter: /usr/bin/python3.8
